//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTZN.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LTZN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bg2 {
            get {
                object obj = ResourceManager.GetObject("bg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bgm {
            get {
                object obj = ResourceManager.GetObject("bgm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bgm1 {
            get {
                object obj = ResourceManager.GetObject("bgm1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bgm3 {
            get {
                object obj = ResourceManager.GetObject("bgm3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap down_10 {
            get {
                object obj = ResourceManager.GetObject("down_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap duote_08 {
            get {
                object obj = ResourceManager.GetObject("duote_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap topcon {
            get {
                object obj = ResourceManager.GetObject("topcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] yuebao_template {
            get {
                object obj = ResourceManager.GetObject("yuebao_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;H1 align=center&gt;厂调指标查询&lt;/H1&gt;
        ///&lt;HR width=&quot;80%&quot;&gt;
        ///
        ///&lt;TABLE height=151 cellPadding=1 align=center bgColor=#cccccc border=0&gt;
        ///&lt;TBODY&gt;
        ///&lt;TR&gt;
        ///&lt;TD align=middle width=40 bgColor=#c6ffc6 height=28&gt;单位&lt;/TD&gt;
        ///&lt;TD align=middle width=40 bgColor=#c6ffc6 height=28&gt;项目&lt;/TD&gt;
        ///&lt;TD align=middle width=66 bgColor=#c6ffc6 height=28&gt;全铁产量&lt;/TD&gt;
        ///&lt;TD align=middle width=64 bgColor=#c6ffc6 height=28&gt;Si≤0.7&lt;/TD&gt;
        ///&lt;TD align=middle width=64 bgColor=#c6ffc6 height=28&gt;送炼钢铁&lt;/TD&gt;
        ///&lt;TD align=middle width=56 bgColor=#c6ffc6 height=28&gt;铸造铁&lt;/TD&gt;
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 上报厂调 {
            get {
                return ResourceManager.GetString("上报厂调", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;H1 align=center&gt;综合厂调指标查询&lt;/H1&gt;
        ///&lt;HR width=&quot;80%&quot;&gt;
        ///
        ///&lt;TABLE height=147 cellPadding=1 align=center bgColor=#cccccc border=0&gt;
        ///&lt;TBODY&gt;
        ///&lt;TR&gt;
        ///&lt;TD align=right width=56 bgColor=#c6ffc6 height=24&gt;单位&lt;/TD&gt;
        ///&lt;TD align=right width=56 bgColor=#c6ffc6 height=24&gt;夜班&lt;/TD&gt;
        ///&lt;TD align=right width=56 bgColor=#c6ffc6 height=24&gt;白班&lt;/TD&gt;
        ///&lt;TD align=right width=56 bgColor=#c6ffc6 height=24&gt;中班&lt;/TD&gt;
        ///&lt;TD align=right width=76 bgColor=#c6ffc6 height=24&gt;全铁产量&lt;/TD&gt;
        ///&lt;TD align=right width=82 bgColor=#c6ffc6 height=24&gt;累计产量&lt;/TD&gt;
        ///&lt;TD align [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 其它数据 {
            get {
                return ResourceManager.GetString("其它数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;HTML&gt;
        ///&lt;HEAD&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt; 
        ///    body{font-size:9pt}
        ///    table{ border-top:1px solid black;border-right:0px solid black;border-bottom:0px solid black;border-left:1px solid black; border-cllapse:collapse;margin:0;padding:0;}  
        ///     TBODY{ border-top:1px solid black;border-right:0px solid black;border-bottom:0px solid black;border-left:1px solid black; border-cllapse:collapse;margin:0;padding:0;} 
        ///    td{border-top:0px solid black;border-right:1px solid black;border-bottom:1px solid black;bo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 技术日报 {
            get {
                return ResourceManager.GetString("技术日报", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;HTML&gt;
        ///&lt;HEAD&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt; 
        ///    body{font-size:9pt}
        ///    table{ border-top:1px solid black;border-right:0px solid black;border-bottom:0px solid black;border-left:1px solid black; border-cllapse:collapse;margin:0;padding:0;}  
        ///     TBODY{ border-top:1px solid black;border-right:0px solid black;border-bottom:0px solid black;border-left:1px solid black; border-cllapse:collapse;margin:0;padding:0;} 
        ///    td{border-top:0px solid black;border-right:1px solid black;border-bottom:1px solid black;bo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 技术月报 {
            get {
                return ResourceManager.GetString("技术月报", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///&lt;BODY style=&quot;BACKGROUND-COLOR: #eeeeff&quot; leftMargin=5 topMargin=25&gt;&lt;H1 align=center&gt;生产指标查询&lt;/H1&gt;
        ///&lt;HR width=&quot;80%&quot;&gt;
        ///
        ///&lt;TABLE cellPadding=1 align=center bgColor=#cccccc border=0&gt;
        ///&lt;TBODY&gt;
        ///&lt;TR&gt;
        ///&lt;TD align=middle width=56 bgColor=#c6ffc6 height=30&gt;单位&lt;/TD&gt;
        ///&lt;TD align=middle width=56 bgColor=#c6ffc6 height=30&gt;夜班&lt;/TD&gt;
        ///&lt;TD align=middle width=56 bgColor=#c6ffc6 height=30&gt;白班&lt;/TD&gt;
        ///&lt;TD align=middle width=56 bgColor=#c6ffc6 height=30&gt;中班&lt;/TD&gt;
        ///&lt;TD align=middle width=66 bgColor=#c6ffc6 height=30&gt;全铁产量&lt;/TD&gt;
        ///&lt;TD align=m [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 本日生铁 {
            get {
                return ResourceManager.GetString("本日生铁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 炼铁技术日报 {
            get {
                object obj = ResourceManager.GetObject("炼铁技术日报", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 炼铁技术月报 {
            get {
                object obj = ResourceManager.GetObject("炼铁技术月报", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 炼铁质量日报 {
            get {
                object obj = ResourceManager.GetObject("炼铁质量日报", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 生产 {
            get {
                object obj = ResourceManager.GetObject("生产", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 调度 {
            get {
                object obj = ResourceManager.GetObject("调度", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
