
drop table xiaohao;
create table xiaohao
(
rq              date  not null,
gaolu             number(2) not null,
al2o3             number(10,4),
bengliao          number(10),
cao               number(10,4),
co                number(10,4),
co2               number(10,4),
feitie            number(10,4),
fengkoudatao      number(10),
fengkouxiaotao    number(10),
fengkouzhongtao   number(10),
fengwen           number(10,4),
fenshu            number(10,4),
feo               number(10,4),
fuyang            number(10,4),
gaoyashijian      number(10,4),
jiaoding          number(10,4),
lengfengliuliang  number(10,4),
liaopi            number(10),
ludingwendu       number(10,4),
ludingyali        number(10,4),
lushu             number(10),
mgo               number(10,4),
mno               number(10,4),
refengyali        number(10,4),
s                 number(10,4),
sio2              number(10,4),
waigoufeitie      number(10,4),
shenliaopi        number(10),
shijiaofen        number(10,4),
xuanliao          number(10),
zhakoudatao       number(10),
zhakouxiaotao     number(10),
zhakouzhongtao    number(10),
zuoliao           number(10),
CONSTRAINT "xiaohaopk" PRIMARY KEY(riqi,gaolu) 
);